# Tools for translating extracted data into plottable formats.

#' Calculate the number of active users in a set of date ranges.
#' 
#' @param sesh_dur_data A dataframe of user_ids and the dates when they took a
#' platform action.
#' @param range_beginning A data.table with a single column of dates which 
#' denote the first days of each date range.
#' @return A data frame showing how many active users there were in each date
#' range.
#' @import data.table

calculate_active_users <- function(sesh_dur_data
                                   , range_beginning){
  sesh_dur_data[, rollDate:= platform_action_date]
  data.table::setkey(sesh_dur_data, rollDate)

  range_beginning[, rollDate:= range_beginning_date]
  data.table::setkey(range_beginning, rollDate)

  range_beginning[
    sesh_dur_data
    , .(user_id, platform_action_date, range_beginning_date)
    , roll = T
  ][

    , .(number_of_active_users = length(unique(user_id)))
    , by = range_beginning_date
  ]
}

#' Loop calculate_active_users over a list of date ranges.
#'
#' @param date_ranges A list of date ranges, of the form generated by
#' standardmetrics::define_date_ranges.
#' @return A list of data frames that show the number of active users that fall
#' within each date range.
#' @import data.table

loop_calculate_active_users <- function(date_ranges
                                        , ...){
  lapply(date_ranges
         , FUN = function(r){
           calculate_active_users(..., r)
         })
}

#' Calculate DAU to MAU ratio by month.
#'
#' @param MAU_count_by_month A data.table: (month_beginning MAU_count)
#' @param DAU_count_by_day A data.table: (day DAU_count)  
#' @return A data frame showing the average DAU to MAU ratio for each month
#' specified by months_to_calc.
#' @import data.table

calculate_DAU_MAU_ratio <- function(MAU_count_by_month
                                    , DAU_count_by_day){

  MAU_count_by_month[, c('MAU_count'
                         , 'month_beginning_date'
                         , "rollMonth")
                       := .(number_of_active_users
                            , range_beginning_date
                            , range_beginning_date)]
  data.table::setkey(MAU_count_by_month, rollMonth)

  DAU_count_by_day[, c('DAU_count'
                         , 'day_beginning_date'
                         , "rollDate")
                       := .(number_of_active_users
                            , range_beginning_date
                            , range_beginning_date)]
  data.table::setkey(DAU_count_by_day, rollDate)

  MAU_count_by_month[
    DAU_count_by_day 
    , .(month_beginning_date, day_beginning_date, MAU_count, DAU_count)
    , roll = T
  ][

    , (DAU_to_MAU_ratio = mean(DAU_count)/mean(MAU_count))
    , by = month_beginning_date 
  ]
}
