# Tools for translating extracted data into plottable formats.

#' Calculate the number of active users in a set of date ranges.
#' 
#' @param sesh_dur_data A dataframe of user_ids and the dates when they took a
#' platform action.
#' @param range_beginning A data.table with a single column of dates which 
#' denote the first days of each date range.
#' @return A data frame showing how many active users there were in each date
#' range.
#' @import data.table

calculate_active_users <- function(sesh_dur_data
                                   , range_beginning){
  sesh_dur_data[, rollDate:= platform_action_date]
  data.table::setkey(sesh_dur_data, rollDate)

  range_beginning[, rollDate:= range_beginning_date]
  data.table::setkey(range_beginning, rollDate)

  range_beginning[
    sesh_dur_data
    , .(user_id, platform_action_date, range_beginning_date)
    , roll = T
  ][

    , .(number_of_active_users = length(unique(user_id)))
    , by = range_beginning_date
  ]
}

#' Loop calculate_active_users over a list of date ranges.
#'
#' @param date_ranges A list of date ranges, of the form generated by
#' standardmetrics::define_date_ranges.
#' @return A list of data frames that show the number of active users that fall
#' within each date range.

loop_calculate_active_users <- function(date_ranges
                                        , ...){
  lapply(date_ranges
         , FUN = function(r){
           calculate_active_users(..., r)
         })
}

#' Convert platform action datetimes to difftimes relative to first platform
#' action, and relative to first day.
#'
#' @param upd A data frame: (user_id, datetime) where datetime is a chron
#' object representing the moment a platform action was taken.
#' @return A data frame: (user_id, relative_time, relative_date) where
#' relative_* are difftime objects. relative_time represents the amount of seconds that have
#' passed since their first platform action. relative_date represents the
#' amount of days that have passed since the first day of their platform
#' action.
#' @import data.table

find_relative_pa_datetimes <- function(upd){
  upd[
    , date := lubridate::date(datetime)
  ][
    , c("user_id", "signup_datetime", "signup_date") := .(user_id, min(datetime), min(date))
    , by = user_id
  ][
    , c('user_id', 'relative_datetime', 'relative_date') 
        := .(user_id
             , difftime(datetime, signup_datetime, units = 'mins')
             , difftime(date, signup_date, units = 'days'))
  ][
    , .(user_id, relative_datetime, relative_date)
  ]
}

#' Classify users as 1d7 or regular.
#'
#' @param updr A data frame: (user_id, relative_datetime, relative_date). The
#' result of calling find_relative_pa_datetimes.
#' @return A data frame: (user_id, 1d7). The field 1d7 is logical; true if the
#' user returned to Gloo in their first week after signup and false otherwise.
#' @import data.table

classify_1d7s <- function(updr){
  updr[
    , c('user_id'
        , 'day_1_action'
        , 'week_1_action') :=
      .(user_id
        , relative_datetime >= 30 & relative_datetime <= 24*60
        , relative_date >= 2 & relative_date <= 7)
  ][
    , "oneD7" :=
      .(any(day_1_action) | any(week_1_action))
    , by = user_id
  ][
    , .(user_id, oneD7)
  ]
}
